server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
spring:
  application:
    name: "Authentication-CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  base-path: /api/v1
  paths:
    users: "/usuarios"
    roles: "/roles"
    auth: "/autenticacion"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "chupaelperro"

